from .connection import (
    client,
    db,
    id_cache_collection,
    init_indexes,
    jikan_cache_collection,
    users_collection,
)
from .ids import (
    cache_ids,
    get_cached_ids,
    get_cached_ids_by_anilist,
    get_cached_ids_by_mal,
    get_cached_ids_by_mal_bulk,
    get_cached_ids_by_simkl,
)
from .media import (
    JIKAN_CACHE_TTL_HOURS,
    cache_anilist_media,
    get_al_cover,
    get_cached_anilist_media,
    get_jikan_filler_cache,
    set_jikan_filler_cache,
)
from .tokens import (
    get_or_refresh_mal_token,
    handle_invalid_anilist_token,
    handle_invalid_mal_token,
    handle_invalid_simkl_token,
    is_anilist_in_cooldown,
    reset_anilist_error_counter,
    reset_mal_error_counter,
    reset_simkl_error_counter,
)
from .users import (
    find_user_by_anilist_id,
    find_user_by_mal_id,
    find_user_by_simkl_id,
    get_user,
    store_user,
)
from .watchlist import (
    get_user_anime_meta_status,
    get_user_watch_progress,
    invalidate_user_watchlist_cache,
    update_user_watchlist_cache_progress,
)

__all__ = [
    "client",
    "db",
    "users_collection",
    "id_cache_collection",
    "jikan_cache_collection",
    "init_indexes",
    "get_user",
    "find_user_by_mal_id",
    "find_user_by_anilist_id",
    "find_user_by_simkl_id",
    "store_user",
    "is_anilist_in_cooldown",
    "reset_anilist_error_counter",
    "handle_invalid_anilist_token",
    "get_or_refresh_mal_token",
    "reset_mal_error_counter",
    "handle_invalid_mal_token",
    "reset_simkl_error_counter",
    "handle_invalid_simkl_token",
    "invalidate_user_watchlist_cache",
    "get_user_watch_progress",
    "get_user_anime_meta_status",
    "update_user_watchlist_cache_progress",
    "get_cached_ids",
    "get_cached_ids_by_mal",
    "get_cached_ids_by_mal_bulk",
    "get_cached_ids_by_anilist",
    "get_cached_ids_by_simkl",
    "cache_ids",
    "JIKAN_CACHE_TTL_HOURS",
    "get_jikan_filler_cache",
    "set_jikan_filler_cache",
    "get_cached_anilist_media",
    "cache_anilist_media",
    "get_al_cover",
]
